version: '2'
services:
  base:
    image: node:${NODE_VERSION}
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - ${APP_PATH}:/usr/src/service
    working_dir: /usr/src/service/

  install:
    extends:
      service: base
    command: npm i

volumes:
  nodemodules:
    external: true
